config/routes.rb
SoccerPlace::Application.routes.draw do
  resources :coments

  resources :canchas_futbols

  resources :alquilers

  resources :cancha_futbols

  resources :evento_deportivos

  resources :publicidades

  resources :publicidads

  resources :serv_adicionales

 

  resources :comentarios

  resources :turnos

  resources :usuarios

  resources :users

  resources :personas2s

  resources :people

  resources :personas

  resources :locals

end

app/models/alquiler.rb
class Alquiler < ActiveRecord::Base
  belongs_to :cancha_futbol
  belongs_to :usuarios
end

app/models/cancha_futbol.rb
class CanchaFutbol < ActiveRecord::Base
  belongs_to :turnos
  belongs_to :locals
  has_many:comentarios
end

app/models/canchas_futbol.rb
class CanchasFutbol < ActiveRecord::Base
  belongs_to :turnos
  belongs_to :locals
  has_many :coments
 
end

app/models/coment.rb
class Coment < ActiveRecord::Base
  belongs_to :canchas_futbols
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :canchas_futbol
end

app/models/evento_deportivo.rb
class EventoDeportivo < ActiveRecord::Base
end

app/models/local.rb
class Local < ActiveRecord::Base
attr_accessible :nombre, :direccion, :distrito, :latitude, :longitude, :telefono_fijo
geocoded_by :direccion,:distrito => :dir
after_validation :geocode
has_many:canchas_futbols
end

app/models/publicidad.rb
class Publicidad < ActiveRecord::Base
end

app/models/publicidade.rb
class Publicidade < ActiveRecord::Base
end

app/models/serv_adicionale.rb
class ServAdicionale < ActiveRecord::Base
end

app/models/turno.rb
class Turno < ActiveRecord::Base
has_many :canchas_futbols
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/controllers/evento_deportivos_controller.rb
class EventoDeportivosController < ApplicationController
  # GET /evento_deportivos
  # GET /evento_deportivos.json
  def index
    @evento_deportivos = EventoDeportivo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @evento_deportivos }
    end
  end

  # GET /evento_deportivos/1
  # GET /evento_deportivos/1.json
  def show
    @evento_deportivo = EventoDeportivo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @evento_deportivo }
    end
  end

  # GET /evento_deportivos/new
  # GET /evento_deportivos/new.json
  def new
    @evento_deportivo = EventoDeportivo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @evento_deportivo }
    end
  end

  # GET /evento_deportivos/1/edit
  def edit
    @evento_deportivo = EventoDeportivo.find(params[:id])
  end

  # POST /evento_deportivos
  # POST /evento_deportivos.json
  def create
    @evento_deportivo = EventoDeportivo.new(params[:evento_deportivo])

    respond_to do |format|
      if @evento_deportivo.save
        format.html { redirect_to @evento_deportivo, notice: 'Evento deportivo was successfully created.' }
        format.json { render json: @evento_deportivo, status: :created, location: @evento_deportivo }
      else
        format.html { render action: "new" }
        format.json { render json: @evento_deportivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /evento_deportivos/1
  # PUT /evento_deportivos/1.json
  def update
    @evento_deportivo = EventoDeportivo.find(params[:id])

    respond_to do |format|
      if @evento_deportivo.update_attributes(params[:evento_deportivo])
        format.html { redirect_to @evento_deportivo, notice: 'Evento deportivo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @evento_deportivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evento_deportivos/1
  # DELETE /evento_deportivos/1.json
  def destroy
    @evento_deportivo = EventoDeportivo.find(params[:id])
    @evento_deportivo.destroy

    respond_to do |format|
      format.html { redirect_to evento_deportivos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/alquilers_helper.rb
module AlquilersHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/evento_deportivos_helper.rb
module EventoDeportivosHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/personas2s_helper.rb
module Personas2sHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/evento_deportivos/_form.html.erb
<%= form_for(@evento_deportivo) do |f| %>
  <% if @evento_deportivo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evento_deportivo.errors.count, "error") %> prohibited this evento_deportivo from being saved:</h2>

      <ul>
      <% @evento_deportivo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :premio %><br />
    <%= f.text_field :premio %>
  </div>
  <div class="field">
    <%= f.label :CantidadLinEq %><br />
    <%= f.number_field :CantidadLinEq %>
  </div>
  <div class="field">
    <%= f.label :plazoinscripcion %><br />
    <%= f.text_field :plazoinscripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/evento_deportivos/edit.html.erb
<h1>Editing evento_deportivo</h1>

<%= render 'form' %>

<%= link_to 'Show', @evento_deportivo %> |
<%= link_to 'Back', evento_deportivos_path %>

app/views/evento_deportivos/index.html.erb
<h1>Listing evento_deportivos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Premio</th>
    <th>Cantidadlineq</th>
    <th>Plazoinscripcion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @evento_deportivos.each do |evento_deportivo| %>
  <tr>
    <td><%= evento_deportivo.nombre %></td>
    <td><%= evento_deportivo.premio %></td>
    <td><%= evento_deportivo.CantidadLinEq %></td>
    <td><%= evento_deportivo.plazoinscripcion %></td>
    <td><%= link_to 'Show', evento_deportivo %></td>
    <td><%= link_to 'Edit', edit_evento_deportivo_path(evento_deportivo) %></td>
    <td><%= link_to 'Destroy', evento_deportivo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Evento deportivo', new_evento_deportivo_path %>

app/views/evento_deportivos/new.html.erb
<h1>New evento_deportivo</h1>

<%= render 'form' %>

<%= link_to 'Back', evento_deportivos_path %>

app/views/evento_deportivos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @evento_deportivo.nombre %>
</p>

<p>
  <b>Premio:</b>
  <%= @evento_deportivo.premio %>
</p>

<p>
  <b>Cantidadlineq:</b>
  <%= @evento_deportivo.CantidadLinEq %>
</p>

<p>
  <b>Plazoinscripcion:</b>
  <%= @evento_deportivo.plazoinscripcion %>
</p>


<%= link_to 'Edit', edit_evento_deportivo_path(@evento_deportivo) %> |
<%= link_to 'Back', evento_deportivos_path %>