config/routes.rb
SoccerPlace::Application.routes.draw do
  resources :coments

  resources :canchas_futbols

  resources :alquilers

  resources :cancha_futbols

  resources :evento_deportivos

  resources :publicidades

  resources :publicidads

  resources :serv_adicionales

 

  resources :comentarios

  resources :turnos

  resources :usuarios

  resources :users

  resources :personas2s

  resources :people

  resources :personas

  resources :locals

end

app/models/alquiler.rb
class Alquiler < ActiveRecord::Base
  belongs_to :cancha_futbol
  belongs_to :usuarios
end

app/models/cancha_futbol.rb
class CanchaFutbol < ActiveRecord::Base
  belongs_to :turnos
  belongs_to :locals
  has_many:comentarios
end

app/models/canchas_futbol.rb
class CanchasFutbol < ActiveRecord::Base
  belongs_to :turnos
  belongs_to :locals
  has_many :coments
 
end

app/models/coment.rb
class Coment < ActiveRecord::Base
  belongs_to :canchas_futbols
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :canchas_futbol
end

app/models/evento_deportivo.rb
class EventoDeportivo < ActiveRecord::Base
end

app/models/local.rb
class Local < ActiveRecord::Base
attr_accessible :nombre, :direccion, :distrito, :latitude, :longitude, :telefono_fijo
geocoded_by :direccion,:distrito => :dir
after_validation :geocode
has_many:canchas_futbols
end

app/models/publicidad.rb
class Publicidad < ActiveRecord::Base
end

app/models/publicidade.rb
class Publicidade < ActiveRecord::Base
end

app/models/serv_adicionale.rb
class ServAdicionale < ActiveRecord::Base
end

app/models/turno.rb
class Turno < ActiveRecord::Base
has_many :canchas_futbols
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/controllers/publicidades_controller.rb
class PublicidadesController < ApplicationController
  # GET /publicidades
  # GET /publicidades.json
  def index
    @publicidades = Publicidade.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @publicidades }
    end
  end

  # GET /publicidades/1
  # GET /publicidades/1.json
  def show
    @publicidade = Publicidade.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @publicidade }
    end
  end

  # GET /publicidades/new
  # GET /publicidades/new.json
  def new
    @publicidade = Publicidade.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @publicidade }
    end
  end

  # GET /publicidades/1/edit
  def edit
    @publicidade = Publicidade.find(params[:id])
  end

  # POST /publicidades
  # POST /publicidades.json
  def create
    @publicidade = Publicidade.new(params[:publicidade])

    respond_to do |format|
      if @publicidade.save
        format.html { redirect_to @publicidade, notice: 'Publicidade was successfully created.' }
        format.json { render json: @publicidade, status: :created, location: @publicidade }
      else
        format.html { render action: "new" }
        format.json { render json: @publicidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /publicidades/1
  # PUT /publicidades/1.json
  def update
    @publicidade = Publicidade.find(params[:id])

    respond_to do |format|
      if @publicidade.update_attributes(params[:publicidade])
        format.html { redirect_to @publicidade, notice: 'Publicidade was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @publicidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publicidades/1
  # DELETE /publicidades/1.json
  def destroy
    @publicidade = Publicidade.find(params[:id])
    @publicidade.destroy

    respond_to do |format|
      format.html { redirect_to publicidades_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/alquilers_helper.rb
module AlquilersHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/personas2s_helper.rb
module Personas2sHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/publicidades_helper.rb
module PublicidadesHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/publicidades/_form.html.erb
<%= form_for(@publicidade) do |f| %>
  <% if @publicidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publicidade.errors.count, "error") %> prohibited this publicidade from being saved:</h2>

      <ul>
      <% @publicidade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :contenido %><br />
    <%= f.text_field :contenido %>
  </div>
  <div class="field">
    <%= f.label :FecInicio %><br />
    <%= f.text_field :FecInicio %>
  </div>
  <div class="field">
    <%= f.label :FecFin %><br />
    <%= f.text_field :FecFin %>
  </div>
  <div class="field">
    <%= f.label :Tarifa %><br />
    <%= f.text_field :Tarifa %>
  </div>
  <div class="field">
    <%= f.label :num_clicks %><br />
    <%= f.number_field :num_clicks %>
  </div>
  <div class="field">
    <%= f.label :ubicacion %><br />
    <%= f.number_field :ubicacion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publicidades/edit.html.erb
<h1>Editing publicidade</h1>

<%= render 'form' %>

<%= link_to 'Show', @publicidade %> |
<%= link_to 'Back', publicidades_path %>

app/views/publicidades/index.html.erb
<h1>Listing publicidades</h1>

<table>
  <tr>
    <th>Titulo</th>
    <th>Contenido</th>
    <th>Fecinicio</th>
    <th>Fecfin</th>
    <th>Tarifa</th>
    <th>Num clicks</th>
    <th>Ubicacion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @publicidades.each do |publicidade| %>
  <tr>
    <td><%= publicidade.titulo %></td>
    <td><%= publicidade.contenido %></td>
    <td><%= publicidade.FecInicio %></td>
    <td><%= publicidade.FecFin %></td>
    <td><%= publicidade.Tarifa %></td>
    <td><%= publicidade.num_clicks %></td>
    <td><%= publicidade.ubicacion %></td>
    <td><%= link_to 'Show', publicidade %></td>
    <td><%= link_to 'Edit', edit_publicidade_path(publicidade) %></td>
    <td><%= link_to 'Destroy', publicidade, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Publicidade', new_publicidade_path %>

app/views/publicidades/new.html.erb
<h1>New publicidade</h1>

<%= render 'form' %>

<%= link_to 'Back', publicidades_path %>

app/views/publicidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @publicidade.titulo %>
</p>

<p>
  <b>Contenido:</b>
  <%= @publicidade.contenido %>
</p>

<p>
  <b>Fecinicio:</b>
  <%= @publicidade.FecInicio %>
</p>

<p>
  <b>Fecfin:</b>
  <%= @publicidade.FecFin %>
</p>

<p>
  <b>Tarifa:</b>
  <%= @publicidade.Tarifa %>
</p>

<p>
  <b>Num clicks:</b>
  <%= @publicidade.num_clicks %>
</p>

<p>
  <b>Ubicacion:</b>
  <%= @publicidade.ubicacion %>
</p>


<%= link_to 'Edit', edit_publicidade_path(@publicidade) %> |
<%= link_to 'Back', publicidades_path %>