config/routes.rb
SoccerPlace::Application.routes.draw do
  resources :coments

  resources :canchas_futbols

  resources :alquilers

  resources :cancha_futbols

  resources :evento_deportivos

  resources :publicidades

  resources :publicidads

  resources :serv_adicionales

 

  resources :comentarios

  resources :turnos

  resources :usuarios

  resources :users

  resources :personas2s

  resources :people

  resources :personas

  resources :locals

end

app/models/alquiler.rb
class Alquiler < ActiveRecord::Base
  belongs_to :cancha_futbol
  belongs_to :usuarios
end

app/models/cancha_futbol.rb
class CanchaFutbol < ActiveRecord::Base
  belongs_to :turnos
  belongs_to :locals
  has_many:comentarios
end

app/models/canchas_futbol.rb
class CanchasFutbol < ActiveRecord::Base
  belongs_to :turnos
  belongs_to :locals
  has_many :coments
 
end

app/models/coment.rb
class Coment < ActiveRecord::Base
  belongs_to :canchas_futbols
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :canchas_futbol
end

app/models/evento_deportivo.rb
class EventoDeportivo < ActiveRecord::Base
end

app/models/local.rb
class Local < ActiveRecord::Base
attr_accessible :nombre, :direccion, :distrito, :latitude, :longitude, :telefono_fijo
geocoded_by :direccion,:distrito => :dir
after_validation :geocode
has_many:canchas_futbols
end

app/models/publicidad.rb
class Publicidad < ActiveRecord::Base
end

app/models/publicidade.rb
class Publicidade < ActiveRecord::Base
end

app/models/serv_adicionale.rb
class ServAdicionale < ActiveRecord::Base
end

app/models/turno.rb
class Turno < ActiveRecord::Base
has_many :canchas_futbols
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/controllers/alquilers_controller.rb
class AlquilersController < ApplicationController
  # GET /alquilers
  # GET /alquilers.json
  def index
    @alquilers = Alquiler.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @alquilers }
    end
  end

  # GET /alquilers/1
  # GET /alquilers/1.json
  def show
    @alquiler = Alquiler.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @alquiler }
    end
  end

  # GET /alquilers/new
  # GET /alquilers/new.json
  def new
    @alquiler = Alquiler.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @alquiler }
    end
  end

  # GET /alquilers/1/edit
  def edit
    @alquiler = Alquiler.find(params[:id])
  end

  # POST /alquilers
  # POST /alquilers.json
  def create
    @alquiler = Alquiler.new(params[:alquiler])

    respond_to do |format|
      if @alquiler.save
        format.html { redirect_to @alquiler, notice: 'Alquiler was successfully created.' }
        format.json { render json: @alquiler, status: :created, location: @alquiler }
      else
        format.html { render action: "new" }
        format.json { render json: @alquiler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /alquilers/1
  # PUT /alquilers/1.json
  def update
    @alquiler = Alquiler.find(params[:id])

    respond_to do |format|
      if @alquiler.update_attributes(params[:alquiler])
        format.html { redirect_to @alquiler, notice: 'Alquiler was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @alquiler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alquilers/1
  # DELETE /alquilers/1.json
  def destroy
    @alquiler = Alquiler.find(params[:id])
    @alquiler.destroy

    respond_to do |format|
      format.html { redirect_to alquilers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/alquilers_helper.rb
module AlquilersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/personas2s_helper.rb
module Personas2sHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/alquilers/_form.html.erb
<%= form_for(@alquiler) do |f| %>
  <% if @alquiler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alquiler.errors.count, "error") %> prohibited this alquiler from being saved:</h2>

      <ul>
      <% @alquiler.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha %><br />
    <%= f.text_field :fecha %>

	
  </div>
  <div class="field">
    <%= f.label :HoraIni %><br />
    <%= f.text_field :HoraIni %>
  </div>
  <div class="field">
    <%= f.label :HoraFin %><br />
    <%= f.text_field :HoraFin %>
  </div>
  <div class="field">
    <%= f.label :cancha_futbol %><br />
    <%= f.collection_select :cancha_futbol_id, CanchaFutbol.all, :id, :nombre, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :usuarios %><br />
    <%= f.collection_select :usuarios_id, Usuario.all, :id, :nombre, :prompt => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alquilers/edit.html.erb
<h1>Editing alquiler</h1>

<%= render 'form' %>

<%= link_to 'Show', @alquiler %> |
<%= link_to 'Back', alquilers_path %>

app/views/alquilers/index.html.erb
<h1>Listing alquilers</h1>

<table>
  <tr>
    <th>Fecha</th>
    <th>Horaini</th>
    <th>Horafin</th>
    <th>Cancha futbol</th>
    <th>Usuarios</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @alquilers.each do |alquiler| %>
  <tr>
    <td><%= alquiler.fecha %></td>
    <td><%= alquiler.HoraIni %></td>
    <td><%= alquiler.HoraFin %></td>
    <td><%= alquiler.cancha_futbol.nombre %></td>
    <td><%= alquiler.usuarios.nombre %></td>
    <td><%= link_to 'Show', alquiler %></td>
    <td><%= link_to 'Edit', edit_alquiler_path(alquiler) %></td>
    <td><%= link_to 'Destroy', alquiler, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Alquiler', new_alquiler_path %>

app/views/alquilers/new.html.erb
<h1>New alquiler</h1>

<%= render 'form' %>

<%= link_to 'Back', alquilers_path %>

app/views/alquilers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Fecha:</b>
  <%= @alquiler.fecha %>
</p>

<p>
  <b>Horaini:</b>
  <%= @alquiler.HoraIni %>
</p>

<p>
  <b>Horafin:</b>
  <%= @alquiler.HoraFin %>
</p>

<p>
  <b>Cancha futbol:</b>
  <%= @alquiler.cancha_futbol %>
</p>

<p>
  <b>Usuarios:</b>
  <%= @alquiler.usuarios %>
</p>


<%= link_to 'Edit', edit_alquiler_path(@alquiler) %> |
<%= link_to 'Back', alquilers_path %>