config/routes.rb
SoccerPlace::Application.routes.draw do
  resources :coments

  resources :canchas_futbols

  resources :alquilers

  resources :cancha_futbols

  resources :evento_deportivos

  resources :publicidades

  resources :publicidads

  resources :serv_adicionales

 

  resources :comentarios

  resources :turnos

  resources :usuarios

  resources :users

  resources :personas2s

  resources :people

  resources :personas

  resources :locals

end

app/models/alquiler.rb
class Alquiler < ActiveRecord::Base
  belongs_to :cancha_futbol
  belongs_to :usuarios
end

app/models/cancha_futbol.rb
class CanchaFutbol < ActiveRecord::Base
  belongs_to :turnos
  belongs_to :locals
  has_many:comentarios
end

app/models/canchas_futbol.rb
class CanchasFutbol < ActiveRecord::Base
  belongs_to :turnos
  belongs_to :locals
  has_many :coments
 
end

app/models/coment.rb
class Coment < ActiveRecord::Base
  belongs_to :canchas_futbols
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :canchas_futbol
end

app/models/evento_deportivo.rb
class EventoDeportivo < ActiveRecord::Base
end

app/models/local.rb
class Local < ActiveRecord::Base
attr_accessible :nombre, :direccion, :distrito, :latitude, :longitude, :telefono_fijo
geocoded_by :direccion,:distrito => :dir
after_validation :geocode
has_many:canchas_futbols
end

app/models/publicidad.rb
class Publicidad < ActiveRecord::Base
end

app/models/publicidade.rb
class Publicidade < ActiveRecord::Base
end

app/models/serv_adicionale.rb
class ServAdicionale < ActiveRecord::Base
end

app/models/turno.rb
class Turno < ActiveRecord::Base
has_many :canchas_futbols
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/controllers/canchas_futbols_controller.rb
class CanchasFutbolsController < ApplicationController
  # GET /canchas_futbols
  # GET /canchas_futbols.json
  def index
    @canchas_futbols = CanchasFutbol.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @canchas_futbols }
    end
  end

  # GET /canchas_futbols/1
  # GET /canchas_futbols/1.json
  def show
    @canchas_futbol = CanchasFutbol.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @canchas_futbol }
    end
  end

  # GET /canchas_futbols/new
  # GET /canchas_futbols/new.json
  def new
    @canchas_futbol = CanchasFutbol.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @canchas_futbol }
    end
  end

  # GET /canchas_futbols/1/edit
  def edit
    @canchas_futbol = CanchasFutbol.find(params[:id])
  end

  # POST /canchas_futbols
  # POST /canchas_futbols.json
  def create
    @canchas_futbol = CanchasFutbol.new(params[:canchas_futbol])

    respond_to do |format|
      if @canchas_futbol.save
        format.html { redirect_to @canchas_futbol, notice: 'Canchas futbol was successfully created.' }
        format.json { render json: @canchas_futbol, status: :created, location: @canchas_futbol }
      else
        format.html { render action: "new" }
        format.json { render json: @canchas_futbol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /canchas_futbols/1
  # PUT /canchas_futbols/1.json
  def update
    @canchas_futbol = CanchasFutbol.find(params[:id])

    respond_to do |format|
      if @canchas_futbol.update_attributes(params[:canchas_futbol])
        format.html { redirect_to @canchas_futbol, notice: 'Canchas futbol was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @canchas_futbol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /canchas_futbols/1
  # DELETE /canchas_futbols/1.json
  def destroy
    @canchas_futbol = CanchasFutbol.find(params[:id])
    @canchas_futbol.destroy

    respond_to do |format|
      format.html { redirect_to canchas_futbols_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/alquilers_helper.rb
module AlquilersHelper
end

app/helpers/canchas_futbols_helper.rb
module CanchasFutbolsHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/personas2s_helper.rb
module Personas2sHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/canchas_futbols/_form.html.erb
<%= form_for(@canchas_futbol) do |f| %>
  <% if @canchas_futbol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@canchas_futbol.errors.count, "error") %> prohibited this canchas_futbol from being saved:</h2>

      <ul>
      <% @canchas_futbol.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :caracteristicas %><br />
    <%= f.text_field :caracteristicas %>
  </div>
  <div class="field">
    <%= f.label :tarifa %><br />
    <%= f.text_field :tarifa %>
  </div>
  <div class="field">
    <%= f.label :promocion %><br />
    <%= f.text_field :promocion %>
  </div>
  <div class="field">
    <%= f.label :turnos %><br />
    <%= f.collection_select :turnos_id, Turno.all, :id, :nombre, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :locals %><br />
    <%= f.collection_select :locals_id, Local.all, :id, :nombre, :prompt => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/canchas_futbols/edit.html.erb
<h1>Editing canchas_futbol</h1>

<%= render 'form' %>

<%= link_to 'Show', @canchas_futbol %> |
<%= link_to 'Back', canchas_futbols_path %>

app/views/canchas_futbols/index.html.erb
<h1>Listing canchas_futbols</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Caracteristicas</th>
    <th>Tarifa</th>
    <th>Promocion</th>
    <th>Turnos</th>
    <th>Locals</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @canchas_futbols.each do |canchas_futbol| %>
  <tr>
    <td><%= canchas_futbol.nombre %></td>
    <td><%= canchas_futbol.caracteristicas %></td>
    <td><%= canchas_futbol.tarifa %></td>
    <td><%= canchas_futbol.promocion %></td>

    <td><%= link_to 'Show', canchas_futbol %></td>
    <td><%= link_to 'Edit', edit_canchas_futbol_path(canchas_futbol) %></td>
    <td><%= link_to 'Destroy', canchas_futbol, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Canchas futbol', new_canchas_futbol_path %>

app/views/canchas_futbols/new.html.erb
<h1>New canchas_futbol</h1>

<%= render 'form' %>

<%= link_to 'Back', canchas_futbols_path %>

app/views/canchas_futbols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @canchas_futbol.nombre %>
</p>

<p>
  <b>Caracteristicas:</b>
  <%= @canchas_futbol.caracteristicas %>
</p>

<p>
  <b>Tarifa:</b>
  <%= @canchas_futbol.tarifa %>
</p>

<p>
  <b>Promocion:</b>
  <%= @canchas_futbol.promocion %>
</p>

<p>
  <b>Turnos:</b>
  <%= @canchas_futbol.turnos %>
</p>

<p>
  <b>Locals:</b>
  <%= @canchas_futbol.locals %>
</p>


<%= link_to 'Edit', edit_canchas_futbol_path(@canchas_futbol) %> |
<%= link_to 'Back', canchas_futbols_path %>